# Generated by Django 6.0.1 on 2026-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0003_alter_question_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_quizzes',
            field=models.ManyToManyField(blank=True, to='courses.quiz'),
        ),
    ]
