# Generated by Django 6.0.1 on 2026-02-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
