# Generated by Django 6.0.1 on 2026-01-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_certificate_hash_alter_certificate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
