# Generated by Django 6.0.1 on 2026-01-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_certificate_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='hash',
        ),
    ]
